### ISSUE TITLE
BUG: Website is not access able on iPhone and Mac Safari! Only Chrome on macOS works

### ISSUE THREAD

**Issue by URBANsUNITED** [bonukai/MediaTracker#119]
Hi!

The website is not access able on my iPhone. 
On the Mac using Chrome no issues, but Safari doesn't work either! Only Chrome works.

Will this help?
![Bildschirmfoto 2022-02-09 um 19 21 44](https://user-images.githubusercontent.com/6212300/153265208-638f777e-61e8-4423-b94a-9a9f4a7b75b0.png)

![Bildschirmfoto 2022-02-09 um 19 21 09](https://user-images.githubusercontent.com/6212300/153265259-ed710594-12d0-4596-a6ae-ca5894375cb7.png)

Thanks

URBANsUNITED

**Comment by bonukai** [comment]
Yes, it was very helpful. 

I don't have a Mac or an iPhone, so I can't test it, but I think it should be working now, could you check

**Comment by URBANsUNITED** [comment]
Not yet solved, new error:
![Bildschirmfoto 2022-02-09 um 20 15 39](https://user-images.githubusercontent.com/6212300/153273657-cf7cd2f4-3c5a-4f25-87c1-2d2623adaf3c.png)
![Bildschirmfoto 2022-02-09 um 20 16 32](https://user-images.githubusercontent.com/6212300/153273854-8eaf364f-430a-4b0a-a0b1-aae04415a17c.png)

**Comment by bonukai** [comment]
Can you try again?

**Comment by URBANsUNITED** [comment]
WORKS! 👍🏼
Great! Many thanks ☺️
But the picture rendering is much slower then on Chrome. On the same machine.
iPhone Safari and Chrome = equal speed, but on macOS is Chrome much faster compared to Safari.
I am talking about the transform from blur to sharp picture to full sharp. 
The dev console gave no error, maybe a general "problem"!?! iPhone is an 11'er, so power enough...

Cheers

**Comment by bonukai** [comment]
Perhaps there is some issue with react-spring and safari, like [here](https://github.com/pmndrs/react-spring/issues/1085). I'll set up virtual machine with macOS next week and try to fix it
